### ISSUE TITLE
Password returned with user record

### ISSUE THREAD

**Issue by ComputerCarl** [eddyystop/feathers-hooks-populate#3]
I am attempting to use the `populate` function for a `message` service.

The resulting `message` object contains a `user` object with the password, although the `users` service has a `commonHooks.discard('password')` hook.

Does the `populate` function bypass the `message`'s service hook? And if so, how do I now filter the password... or better yet.. I only want to return `user.email`.. not the entire user record.

````js
  after: {
    all: [populate({
      user: { // Destination key
        service: 'users', // Foreign service
        f_key: '_id',  // Foreign key
        l_key: 'userId',  // local key
        one: true // Optional, if only one resolve object is wanted
      }
    })
  ],
````

**Comment by eddyystop** [comment]
The params you are using above indicate you are using MichaelErmer/feathers-populate-hook not populate from this repo.

In any case, this repo is deprecated having been absorbed into the official FeathersJS populate hook is found in feathersjs/feathers-hooks-common .
